sudo: false
dist: bionic
language: python
python:
- '3.6'
- '3.7'
install:
- pip install tox-travis
script:
- tox
after_success:
- pip install coveralls
- coveralls
deploy:
  provider: pypi
  user: blairg23
  on:
    branch: master
    tags: true
  password:
    secure: xL3oBijixPh+g5yFKhgjoOd0x+WgBIESvNaA6m/IuXDbHk2DXVwbs02lIy6Lh2Rsnfd5PMn/h2N8MJlAXp6GcORfOLxXgqqADV7gsoOD+ecJwGp+/e9BLTp4OSzjLG+M5fhPnNuqSXKXfC+h6pvCNae9IcPQsm/oQTyt5Iysvq4xlV22wDv0Hh3HXRLOca540TMeOO8tHm8CqgXEjty93tLS28cJWaLf9BNmN1+GvNMpp346suMXAKiaUcuRLpWsKI3pj6u/4UfkitdUTbAOgrvAs7tNMSHsps2nWsQnDwKhC0EgfIKyuM13we1PPayfVZaIeNmNdC00zaLaMRWj65CA2XOudHncShlqmJ9qMdAgw0njaNiCaK8aAvgAMvryjYiurymT1SOJSs3MMvqbhtBkMlOzHzqY//awiw8BhlVIWJvMBHlVr+j30K0nxuzvxgafSJDpU1PduuCz/zqXtKbJiJ1d8FxExwjv7gbCR7XXcftchWQx1VHFUK4jbAOSWOPxKGcn7PUBDJu2ZPurKlxg71lKVjEsmIs8xaGx6bDitgjt6HyTw5Z3QBxsamcrMx9vEIoEhJGzjW0v4nm1nl6iD+Aanjv54IdRGeWRIQtIMxNl1GzRPtJnd+qu29Sqs0OMmCY/8DMFKHVTW9G1+Q85FBa8jjU0qT5oMUe9s6A=
